app = ""
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    soft_limit = 1600
    hard_limit = 2000
    type = "requests"

[[services]]
  protocol = "tcp"
  internal_port = 4000
  processes = ["app"]
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
  soft_limit = 200
  hard_limit = 250
  type = "requests"

  [[services.ports]]
    port = 4000
    handlers = ["tls", "http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
